name: Run Tests for Module Header Files

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
    
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install gtest manually
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
    - uses: actions/checkout@v1
    - name: Cmake
      run: mkdir build && cd build && cmake
      working-directory: ./headers/tests
    - name: Build test project
      run: cd build && make
      working-directory: ./headers/tests
    - name: Execute tests
      run: /home/runner/work/fmi-ls-bus/fmi-ls-bus/headers/tests/build/test/fmi_3_ls_bus_header_test.test
