name: Run Tests for Module Header Files

on:
  workflow_dispatch:
    inputs:
      modules: 
        type: string
        required: true
        default: can,can2
        description: Specify the modules you want to run tests for. Available are 'can' and 'can2'. Example':' 'can';'can2' (case sensitive).

      can2: 
        type: boolean
        required: true
        default: false
        description: Run tests for 'Can2' module.

jobs:
  test-header-files:
    name: Test changed header files
    runs-on: ubuntu-latest

    steps:
    - name: Install googletest
      run: |
        set -e
        sudo apt-get install libgtest-dev
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
    - uses: actions/checkout@v1

    - name: Configure
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DMODULE_LIST=${inputs.modules} ..
      working-directory: ./headers/tests

    - name: Build test project
      run: |
        cd build
        make
      working-directory: ./headers/tests

    - name: Execute tests
      run: /home/runner/work/fmi-ls-bus/fmi-ls-bus/headers/tests/build/test/fmi_3_ls_bus_header_test.test